### ISSUE TITLE
Segfault in settings collector

### ISSUE THREAD

**Issue by greigwise** [weaponry/pgscv#9]
I'm getting a segfault trying to run pgscv on a pgbouncer instance, connecting remotely to my postgres server. If I disable the postgres/settings collector, then I can avoid the segfault. Wondering if maybe it's because I should be running pgscv on the postgres server itself? Even if that is right, I wouldn't expect a segfault. Here is what I'm seeing:

Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: {"level":"warn","service":"pgscv","time":"2021-08-18T18:23:18Z","message":"stat /var/lib/pgsql/12/data/postgresql.conf failed: stat /var/lib/pgsql/12/data/postgresql.conf: no such file or directory; skip"}
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa2fa88]
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: goroutine 50 [running]:
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: github.com/weaponry/pgscv/internal/collector.parsePostgresFiles(0xc000250240, 0xc17bba, 0x77, 0xc000250240)
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/postgres_settings.go:227 +0x1c8
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: github.com/weaponry/pgscv/internal/collector.(*postgresSettingsCollector).Update(0xc0000c2a50, 0xc0000356e8, 0x8, 0xc0000ac270, 0x28, 0x0, 0x0, 0x0, 0x1, 0x2000, ...)
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/postgres_settings.go:77 +0x305
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: github.com/weaponry/pgscv/internal/collector.collect(0xbf70b9, 0x11, 0xc0000356e8, 0x8, 0xc0000ac270, 0x28, 0x0, 0x0, 0x0, 0x1, ...)
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/collector.go:241 +0x85
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: github.com/weaponry/pgscv/internal/collector.PgscvCollector.Collect.func1(0xc000120a00, 0xc00006a360, 0xc0004f8890, 0xbf70b9, 0x11, 0xcc7300, 0xc0000c2a50)
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/collector.go:205 +0xc8
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: created by github.com/weaponry/pgscv/internal/collector.PgscvCollector.Collect
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/collector.go:204 +0x1ed
Aug 18 18:23:18 pool01-qa-uw2.hireology.com systemd[1]: pgscv.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 18 18:23:18 pool01-qa-uw2.hireology.com systemd[1]: Unit pgscv.service entered failed state.
Aug 18 18:23:18 pool01-qa-uw2.hireology.com systemd[1]: pgscv.service failed.

Config file:

listen_address: 0.0.0.0:9890
services:
  "postgresqa":
    service_type: "postgres"
    conninfo: "postgres://pgscv@127.0.0.1:5432/postgres"
  "pgbouncerqa":
    service_type: "pgbouncer"
    conninfo: "postgres://pgbouncer@127.0.0.1:5432/pgbouncer"
defaults:
    pgbouncer_username: "pgbouncer"
    postgres_username: "pgscv"
disable_collectors:
  - system

**Comment by lesovsky** [comment]
Please follow the [template](https://github.com/weaponry/pgscv/issues/new?assignees=&labels=&template=bug_report.md&title=) and provide other important details.

**Comment by greigwise** [comment]
Hopefully, the information below gives you everything you need.

Thanks,
Greig

**Describe the bug**
When pgSCV is started and queried for data, the service segfaults and does not provide any data.  If I turn off the postgres/settings collector in the config file, then the system operates as expected.

**Steps to reproduce**
Install pgSCV on a pgbouncer server.  Start pgSCV with the below configuration file and issue this command:
curl -s http://127.0.0.1:9890/metrics

**Expected behavior**
When the curl command is given I expect to see data returned.  Instead I get nothing.  

**pgSCV startup options**

From service file, pgscv is started as follows:
ExecStart=/var/local/pgscv/0.7.1/pgscv --config-file=/var/local/pgscv/0.7.1/env

Describe used pgSCV configuration options (YAML configuration or environment variables).
This is the YAML config file:

listen_address: 0.0.0.0:9890
services:
  "postgresqa":
    service_type: "postgres"
    conninfo: "postgres://pgscv@127.0.0.1:5432/postgres"
  "pgbouncerqa":
    service_type: "pgbouncer"
    conninfo: "postgres://pgbouncer@127.0.0.1:5432/pgbouncer"
defaults:
    pgbouncer_username: "pgbouncer"
    postgres_username: "pgscv"
disable_collectors:
  - system

**Errors and Logs**

Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: {"level":"warn","service":"pgscv","time":"2021-08-18T18:23:18Z","message":"stat /var/lib/pgsql/12/data/postgresql.conf failed: stat /var/lib/pgsql/12/data/postgresql.conf: no such file or directory; skip"}
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa2fa88]
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: goroutine 50 [running]:
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: github.com/weaponry/pgscv/internal/collector.parsePostgresFiles(0xc000250240, 0xc17bba, 0x77, 0xc000250240)
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/postgres_settings.go:227 +0x1c8
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: github.com/weaponry/pgscv/internal/collector.(*postgresSettingsCollector).Update(0xc0000c2a50, 0xc0000356e8, 0x8, 0xc0000ac270, 0x28, 0x0, 0x0, 0x0, 0x1, 0x2000, ...)
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/postgres_settings.go:77 +0x305
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: github.com/weaponry/pgscv/internal/collector.collect(0xbf70b9, 0x11, 0xc0000356e8, 0x8, 0xc0000ac270, 0x28, 0x0, 0x0, 0x0, 0x1, ...)
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/collector.go:241 +0x85
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: github.com/weaponry/pgscv/internal/collector.PgscvCollector.Collect.func1(0xc000120a00, 0xc00006a360, 0xc0004f8890, 0xbf70b9, 0x11, 0xcc7300, 0xc0000c2a50)
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/collector.go:205 +0xc8
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: created by github.com/weaponry/pgscv/internal/collector.PgscvCollector.Collect
Aug 18 18:23:18 pool01-qa-uw2.hireology.com pgscv[8348]: /home/runner/work/pgscv/pgscv/internal/collector/collector.go:204 +0x1ed
Aug 18 18:23:18 pool01-qa-uw2.hireology.com systemd[1]: pgscv.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 18 18:23:18 pool01-qa-uw2.hireology.com systemd[1]: Unit pgscv.service entered failed state.
Aug 18 18:23:18 pool01-qa-uw2.hireology.com systemd[1]: pgscv.service failed.

**Environment (please complete the following information):**
 - Used OS (or Containers): [output of `cat /etc/os-release`]
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

 - pgSCV Version [output of `pgscv --version`]
 pgscv 0.7.1 e582e5f88ce25c2fdb42c8e0b4d7c07271bb7fbd-release

 - PostgreSQL Version [output of `psql -c 'select version()'`]
 ---------------------------------------------------------------------------------------------------------
 PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
(1 row)

 - Do PostgreSQL and pgSCV are running on the same host?
 No.   I am running on a pgbouncer server.

**Additional context**
The only noteworthy things are that I am running on the pgbouncer server where I can connect just fine to the postgres server and also that if I disable to postgres/settings collector, things seem to work as expected.

**Comment by lesovsky** [comment]
Sorry for the delay. 

You use a bit wrong YAML. Syntactically it is correct, but logically is not. For discovery postgres service you use pgbouncer as a proxy which is incorrect. You have to use direct connection to the Postgres. Try to use the something like the following YAML:
```
services:
  "postgresqa":
    service_type: "postgres"
    conninfo: "postgres://pgscv@10.0.0.10:5432/postgres"
  "pgbouncerqa":
    service_type: "pgbouncer"
    conninfo: "postgres://pgbouncer@127.0.0.1:5432/pgbouncer"
```
In this example, pgscv will connect to Postgres on 10.0.0.1, and to Pgbouncer on 127.0.0.1

**Comment by lesovsky** [comment]
Segfault has been fixed here acdb3dc, will be released in next release.
